# Generated by Django 4.1 on 2023-08-03 04:26

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0003_message_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="books",
            field=models.JSONField(
                blank=True, default=base.models.custom_callable_books, null=True
            ),
        ),
    ]
